### ISSUE TITLE
What about the files in version 0.0.2

### ISSUE THREAD

**Issue by kennynaoh** [raphamorim/origami.js#39]
Hello @raphamorim ,
I am the member of cdnjs project.
We want to host this library.
But there is a question about the old version.
Because there is no `v0.0.2` on [npm](https://www.npmjs.com/package/origamijs), we need to add it on github manually.
But I couldn't find the main file in `v0.0.2`.
Please help me confirm that.
Thanks!

https://github.com/cdnjs/cdnjs/issues/9060

**Comment by raphamorim** [comment]
Sorry about delay @kennynaoh,

I've pushed `v0.0.2` now, thank you for reporting it :)

**Comment by kennynaoh** [comment]
Thanks @raphamorim

**Comment by kennynaoh** [comment]
But I still can't find the file in `v0.0.2` on both npm and git repo.
Did I miss something?
Thanks!

**Comment by raphamorim** [comment]
Really?
What do you thin about forget `v0.0.2` version and consider only `v0.0.3` on?

**Comment by kennynaoh** [comment]
If you don't want to maintain that version, it's fine to us.

**Comment by raphamorim** [comment]
Let's forget `v0.0.2` te-hehe
Thank you @kennynaoh :)

**Comment by kennynaoh** [comment]
Thanks @raphamorim ,
And I found that the `origami.js` in version `v0.5.1` on [npm](https://www.npmjs.com/package/origamijs) shows `v0.5.0`.
https://unpkg.com/origamijs@0.5.1/dist/origami.js
Please help me confirm that.
Thanks!

**Comment by raphamorim** [comment]
That's it. My bad, you can confirm it.

**Comment by kennynaoh** [comment]
What you mean just a typo?
Thanks!

**Comment by kennynaoh** [comment]
@raphamorim 
If yes, I will add it as soon as possible.
Thanks!

**Comment by raphamorim** [comment]
Yes :)

**Comment by kennynaoh** [comment]
:metal:

**Comment by raphamorim** [comment]
\o/

**Comment by kennynaoh** [comment]
How about the license?
It shows `GPL-4.0` in `origami.js`
https://github.com/raphamorim/origami.js/commit/6961433afa3d98d6569dbca7a127f51391613038#diff-4505b1037333f19b725a6743b3953a93R6
But it shows `GPL-3.0` in `package.json`
https://github.com/raphamorim/origami.js/commit/70be72ffb1f3303ee81d40fddcff9aa68e28b742#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R14
Please help me confirm this.
Thanks!

**Comment by raphamorim** [comment]
GPL-3.0.

**Comment by raphamorim** [comment]
Ref: https://github.com/raphamorim/origami.js/issues/42

**Comment by kennynaoh** [comment]
Thanks!
